
#ifndef CMDNO_H_
#define CMDNO_H_

// 命令码定义
typedef enum {

cmd_adx_CoreInit                   ,
cmd_adx_CoreClose                  ,
cmd_adx_Power                      ,
cmd_adx_WriteFloatParam            ,
cmd_adx_WriteIntParam              ,
cmd_adx_WriteMultiParam            ,
cmd_adx_MoveAbsolute               ,
cmd_adx_MoveRelative               ,
cmd_adx_SetOverride                ,
cmd_adx_MoveVelocity               ,
cmd_adx_Halt                       ,
cmd_adx_Stop                       ,
cmd_adx_GroupDisable               ,
cmd_adx_GroupEnable                ,
cmd_adx_AddAxisToGroup             ,
cmd_adx_CreateAxisGroup            ,
cmd_adx_SetKinematics              ,
cmd_adx_MoveLinearAbsolute         ,
cmd_adx_GroupWriteFloatParam       ,
cmd_adx_GroupWriteIntParam         ,
cmd_adx_GroupWriteMultiParam       ,
cmd_adx_GroupSetOverride           ,
cmd_adx_GroupInterrupt             ,
cmd_adx_GroupContinue              ,
cmd_adx_GroupStop                  ,
cmd_adx_GroupSetMcode              ,
cmd_adx_RegisterSetDeviceFun       ,
cmd_adx_RegisterReadDeviceFun      ,
cmd_adx_SetDeviceStatus            ,
cmd_adx_SetGantryConfig            ,
cmd_adx_SetGantryEnable            ,  
cmd_adx_RegisterSetMotorRefPosFun  ,
cmd_adx_RegisterGetMotorActPosFun  ,
cmd_adx_RegisterSetMotorEnableFun  ,
cmd_adx_SetMotorEncoderScale       ,
cmd_adx_SetHomeParam               ,
cmd_adx_GoHome                     ,
cmd_adx_ReadDeviceStatus           ,
cmd_adx_ReadMultiParam             ,
cmd_adx_GroupReadMultiParam        ,
cmd_adx_ReadTargetPos              ,
cmd_adx_ReadTargetVel              ,
cmd_adx_ReadTargetAcc              ,
cmd_adx_ReadTargetJerk             ,
cmd_adx_ReadLogicalPos             ,
cmd_adx_ReadLogicalVel             ,
cmd_adx_ReadLogicalAcc             ,
cmd_adx_ReadLogicalJerk            ,
cmd_adx_ReadMultiLogicalPos        ,
cmd_adx_ReadActualPos              ,
cmd_adx_ReadActualVel              ,
cmd_adx_ReadActualAcc              ,
cmd_adx_ReadActualJerk             ,
cmd_adx_ReadMultiActualPos         ,
cmd_adx_ReadStatus                 ,
cmd_adx_ReadMultiStatus            ,
cmd_adx_GroupReadTargetPos         ,
cmd_adx_GroupReadLogicalPos        ,
cmd_adx_GroupReadLogicalVel        ,
cmd_adx_GroupReadLogicalAcc        ,
cmd_adx_GroupReadLogicalJerk       ,
cmd_adx_GroupReadSpeed             ,
cmd_adx_GroupReadStatus            ,
cmd_adx_ReadFloatParam             ,
cmd_adx_ReadIntParam               ,
cmd_adx_GroupReadFloatParam        ,
cmd_adx_GroupReadIntParam          ,
cmd_adx_CmdMaxNum
} EventType_enum;


#endif // !CMDNO_H_